export const ActionTypes = {
    ADD_USER_PREF: "ADD_USER_PREF",
    LOAD_HALL_DATA: "LOAD_HALL_DATA",
    DECR_USER_SEATS: "DECR_USER_SEATS",
    INCR_USER_SEATS: "INCR_USER_SEATS",
    SET_CHOSEN_SEAT: "SET_CHOSEN_SEAT",
    REMOVE_CHOSEN_SEAT: "REMOVE_CHOSEN_SEAT",
    SET_RESERVED_SEATS: "SET_RESERVED_SEATS",
    SET_PROPOSED_SEATS: "SET_PROPOSED_SEATS",
}
